Add Function Sound
BallballTH/Tom-Khai pull request #18
Opened 2024-03-01 15:49 UTC by faiinrd

add soundbg
add soundef (when stats changed)
download sound here ( https://drive.google.com/drive/folders/15CntEoMqLswA5-n5DFq4wNmKjixRzovr?usp=sharing )
create folder Sound ___  soundf ______ hurt.wav
..........................................|..................... |_____ pop.wav
..........................................|__  sounds ______ musicbg.wav

2024-03-01 16:14 UTC, OrneryCash requested changes

2024-03-01 16:14 UTC, OrneryCash commented on textColoring.cpp
Please delete this file.

2024-03-02 06:42 UTC, OrneryCash approved these changes

2024-03-02 06:57 UTC, BallballTH approved these changes
good good

2024-03-02 07:21 UTC, merged