Ball
BallballTH/Tom-Khai pull request #29
Opened 2024-03-03 20:17 UTC by BallballTH

Add:
- Sound can now be changed when switched Scene (if theres any)
- More sound when died
- More colors on Texts
- function Print ---- depends on terminal's width
- a little delay before print texts to prevent some "shifted text" (sometimes)
- Playagain? when in Ending scene

Fix:
- ImportFile function (statchange)
- ResetSaveFile function

Adjust:
- Print scene,hp sa bar
- dialogues

2024-03-03 20:23 UTC, BallballTH commented
Ex.

![Screenshot 2024-03-04 031309](https://github.com/BallballTH/Tom-Khai/assets/49591895/0ff25f30-ddb8-4980-8604-230c70c9e03a)

2024-03-04 11:19 UTC, OrneryCash requested changes

2024-03-04 11:19 UTC, OrneryCash commented on Dialogue/Options.txt
> +ending3|[r]Leave[\]|Leave|
\ ?

2024-03-04 11:19 UTC, OrneryCash commented on dialogueMaker/dialogueMaker.cpp
> +    {"bla", "\033[38;2;.0;0;0m"}, // black
```suggestion
    {"bla", "\033[38;2;0;0;0m"}, // black
```

2024-03-04 11:47 UTC, BallballTH commented on Dialogue/Options.txt
> +ending3|[r]Leave[\]|Leave|
mb

2024-03-04 11:56 UTC, OrneryCash approved these changes
cool

2024-03-04 12:01 UTC, merged